name: Lighthouse Audit

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run Lighthouse
        run: npx lhci autorun

      - name: 🧾 Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lhci-report/
